server:
  port: 8080
  error:
    include-stacktrace: always

spring:
  application:
    name: MovieApp
  profiles:
    active: default
  data:
    cassandra:
      contact-points: ${CASSANDRA_DB_HOST}
      port: ${CASSANDRA_DB_PORT}
      keyspace-name: ${CASSANDRA_DB_KEYSPACE}
      schema-action: NONE
      local-datacenter: ${CASSANDRA_DB_LOCAL_DATACENTER}
      connection:
        connect-timeout: 5000
        init-query-timeout: 5000
      request:
        timeout: 5000
      consistency-level: LOCAL_QUORUM

# astra:
#   api:
#     application-token: ${ASTRA_DB_APP_TOKEN}
#     database-id: ${ASTRA_DB_ID}
#     database-region: ${ASTRA_DB_REGION}
#     cross-region-fallback: false
#   cql:
#     enabled: true
#     download-scb:
#       enabled: true
#     driver-config:
#       basic:
#         session-keyspace: ${ASTRA_DB_KEYSPACE}
#         request:
#           timeout: 8s
#           consistency: LOCAL_QUORUM
#           page-size: 5000
#       advanced:
#         connection: 
#           init-query-timeout: 10s
#           set-keyspace-timeout: 10s
#         control-connection:
#           timeout: 10s
